config/routes.rb
Rails.application.routes.draw do

  root    'sessions#new'
  get     'login'     =>    'sessions#new'
  get     'signup'    =>    'users#new'
  delete  'logout'    =>    'sessions#destroy'

  resources :tasks do
    put :sort, on: :collection
  end
  resources :users,     except: [:index, :show]
  resources :sessions,  only: [:new, :create, :destroy]
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :user

  default_scope { order("priority ASC") }

  def urgency
    panel_type = "panel "
    if completed
      panel_type += "panel-success"
    else
      if due_on && (due_on - Date.today <= 1)
        panel_type += due_on < Date.today ? "panel-danger":"panel-warning"
      else
        panel_type += "panel-primary"
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, length: { :in => 3..20 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates_length_of :password, :in => 6..20, :on => :create
  has_many :tasks


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

private
  def check_logged_in
    redirect_to login_path, notice: "You must log in first" unless session[:user_id]
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to tasks_path, notice: "Logged in"
    else
      redirect_to login_path, alert: "Incorrect username or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "You have successfully logged out."
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :check_logged_in
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :check_id, only: [:show, :edit, :update, :destroy]

  def sort
    params[:order].each do |key,value|
      Task.find(value[:id]).update_attribute(:priority,value[:position])
    end
    render :nothing => true
  end

  # GET /tasks
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    @task.update(task_params)
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    # redirect_to task, notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def check_id
      redirect_to tasks_path, alert: "You do not have permission to do that." unless @task.user_id == session[:user_id]
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :due_on, :priority, :completed, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_logged_in, except: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]



  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to tasks_path, notice: "You signed up successfully"
    else
      flash.now[:alert] = "Form is invalid"
      render "new"
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Whatcha Going To-Do About It", tasks_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if session[:user_id] %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <li><%= link_to "Create new task", new_task_path %></li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatchaGoingToDo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container col-md-8 col-md-offset-2">
      <%= render 'layouts/navbar' %>
      <p id="notice"><%= notice %></p>
      <p id="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="col-md-4">
  <%= form_for @task do |f| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.hidden_field :user_id, value: session[:user_id] %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :due_on %><br>
      <%= f.date_field :due_on %>
    </div>
    <div class="field">
      <%= f.label :priority %><br>
      <%= f.text_field :priority %>
    </div>
    <div class="actions">
      <%= f.submit 'Submit', class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<div id="task-panel-<%=task.id%>">
  <% if task.user_id == session[:user_id] %>
    <% panel_type = task.urgency %>
    <div class="<%= panel_type %>" data-id="<%= task.id %>">
      <div class="panel-heading">
        <h3 class="panel-title"><%= task.name %>
          <%= link_to '<span class="glyphicon glyphicon-remove" id="destroy-box"></span>'.html_safe, task_path(id: task.id), method: :delete, remote: true, class: 'remove-item btn btn-default btn-xs pull-right' %>
        </h3>
      </div>
      <div class="panel-body">
        <p><%= truncate task.description, length: 50 %></p>
        <% if task.due_on %>
          <p id="complete-by">Complete by: <%= task.due_on %></p>
        <% end %>
          <p>Status: <%= task.completed ? "Complete":"Incomplete"%></p>
          <% btn_text = task.completed ? ("Wait, I'm Not Done!"):("I'm Done!")%>
          <%= link_to btn_text, task_path(id: task.id, task: { completed: !task.completed}), method: :patch, remote: true, class: "btn btn-primary btn-sm outline" %>
      </div>
    </div>
    <% end %>
</div>

app/views/tasks/destroy.js.erb
$("#task-panel-<%=@task.id%>").html(' ')

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="jumbotron col-md-10 col-md-offset-1">
  <h1>Things To Do</h1>
</div>
<div class="tasks">
  <div class="row">
    <div class="col-md-5 col-md-offset-1 sortable">
      <%  if @tasks.any? %>
        <%= render @tasks %>
      <% end%>
    </div>
    <div class="col-md-1 col-md-offset-1">
      <%= link_to 'Create New Task', new_task_path, class: "btn btn-success", id: "done-button" %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1 class="new_header">New Task</h1>
    <%= render 'form' %>

    <%= link_to 'Back', tasks_path, class: "btn btn-default" %>
  </div>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Due on:</strong>
  <%= @task.due_on %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$("#task-panel-<%=@task.id%>").html("<%= j(render partial: 'task', locals:{task: @task})%>")

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Signup for a new account</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> | <%= link_to 'Back', users_path %>